### PR TITLE
Auto-generating API docs for website

### PR DESCRIPTION
**Pull request by kylebarron**
Uses [pdocs](https://timothycrosley.github.io/pdocs/) to create auto-generated API docs for the website.

The `text.mako` file is a template that describes how different parts of the API should be put into Markdown. In this PR, that file is modified to add code blocks around docstrings. Otherwise the docstring text is included as literal Markdown.

Including docstrings as literal markdown can be problematic with unmodified docstrings. When you have

```
Examples
--------
```

in a docstring, that will be rendered in Markdown/HTML as an H1 heading, which makes the page look awful and adds anchors where there shouldn't be.

The following two screenshots give the two options, the first is a docstring rendered in a code block; the second is a modified docstring rendered as Markdown. I think the second looks better, but you'd have to modify your docstrings or figure out how to programmatically change them from the `numpydoc` style to Markdown in the site generation process.

image

image

The below command creates the API documentation. It's not strictly necessary to include all the modules spelled out, but otherwise I believe the `__init__.py`s are included.
```bash
pdocs as_markdown \
    --output_dir docs/ \
    --template_dir docs/pdocs_templates \
    --exclude_source \
    --overwrite \
    rio_tiler.colormap \
    rio_tiler.constants \
    rio_tiler.errors \
    rio_tiler.expression \
    rio_tiler.io.base \
    rio_tiler.io.cogeo \
    rio_tiler.io.stac \
    rio_tiler.mercator \
    rio_tiler.mosaic.methods.base \
    rio_tiler.mosaic.methods.defaults \
    rio_tiler.mosaic.reader \
    rio_tiler.profiles \
    rio_tiler.reader \
    rio_tiler.tasks \
    rio_tiler.utils
```

Then you just run `mkdocs serve`/`mkdocs gh-deploy` as normal.

### CODE REVIEW

**Comment by vincentsarago** [comment]
> I think the second looks better, 

👍 

> but you'd have to modify your docstrings or figure out how to programmatically change them from the numpydoc style to Markdown in the site generation process.

I'm not sure to understand what needs to be modified in the docstrings. Can you add a example in this PR?

**Comment by kylebarron** [comment]
> I'm not sure to understand what needs to be modified in the docstrings

For example, the `rio_tiler.io.cogeo` docstring looks like
```
Cloud Optimized GeoTIFF Reader.

Examples
--------
with COGReader(src_path) as cog:
    cog.tile(...)
# Set global options
with COGReader(src_path, unscale=True, nodata=0) as cog:
    cog.tile(...)
with rasterio.open(src_path) as src_dst:
    with WarpedVRT(src_dst, ...) as vrt_dst:
        with COGReader(None, dataset=vrt_dst) as cog:
            cog.tile(...)
with rasterio.open(src_path) as src_dst:
    with COGReader(None, dataset=src_dst) as cog:
        cog.tile(...)

Attributes
----------
filepath: str
    Cloud Optimized GeoTIFF path.
dataset: rasterio.DatasetReader, optional
    Rasterio dataset.
```

In Markdown, 
```
Examples
--------
```
represents an H1 header, and looks like:

Examples
--------

So if you don't wrap in a code block, the docstring will look super weird because each heading will be treated as an H1 in Markdown.

My modifications above were like:

`````
### Cloud Optimized GeoTIFF Reader.

Examples

```py
with COGReader(src_path) as cog:
    cog.tile(...)
# Set global options
with COGReader(src_path, unscale=True, nodata=0) as cog:
    cog.tile(...)
with rasterio.open(src_path) as src_dst:
    with WarpedVRT(src_dst, ...) as vrt_dst:
        with COGReader(None, dataset=vrt_dst) as cog:
            cog.tile(...)
with rasterio.open(src_path) as src_dst:
    with COGReader(None, dataset=src_dst) as cog:
        cog.tile(...)
```

Attributes

- `filepath`: `str`
    Cloud Optimized GeoTIFF path.
- `dataset`: `rasterio.DatasetReader, optional`
    Rasterio dataset.
`````

**Comment by kylebarron** [comment]
Note that the other way to fix this is to parse the Numpydoc docstring and convert it to better Markdown automatically. Discussion here: https://github.com/timothycrosley/pdocs/issues/4

**Comment by vincentsarago** [comment]
We successfully deployed API docs in https://github.com/cogeotiff/rio-tiler-pds using `mkapi`. I think we should use it also for rio-tiler.

This might need some refactor in the current docstrings.

**Pull request closed without merging**
