### PR TITLE
[715] Enable handling of inverted latitude in reader.point

### PR DESCRIPTION
**Pull request by georgespill**
`reader.point` raises a `PointOutsideBounds` error if the input coordinates are outside the dataset bounds. However, the current implementation assumes that `bounds[1] < bounds[3]`. This is not true for inverted latitude coordinates. This PR updates the implementation to handle the inverted case.

Fixes https://github.com/cogeotiff/rio-tiler/issues/715

See https://github.com/cogeotiff/rio-tiler/pull/696 for a similar issue

### CODE REVIEW

**Comment by vincentsarago** [comment]
thanks @georgespill 

do you thing we should had the same kind of warning as in https://github.com/cogeotiff/rio-tiler/pull/696/files#diff-aee02035a0c41599c6860bf04d8075994bb3f9e5b1d5d0595c0d02c5f4ddf596R50-R53 ?

would you be able to write a quick tests for this 🙏

**Comment by georgespill** [comment]
Yep, adding the warning is a good suggestion. Have added that along with updating tests

**Comment by georgespill** [comment]
@vincentsarago would it be possible to publish a release with this fix included?

**Comment by vincentsarago** [comment]
@georgespill yes, I'm just waiting on https://github.com/cogeotiff/rio-tiler/pull/726 to get merged 🙏

**Pull request merged**
