### PR TITLE
Bring mypy out of pre-commit to type check against imports

### PR DESCRIPTION
**Pull request by kylebarron**
Testing on CI; I can't figure out how to add a section to `tox.ini`. I added (locally, didn't commit)
```
[testenv:typing]
extras = test
commands=
    python -m mypy --config-file setup.cfg -p rio_tiler
deps=
    numpy
```
but it didn't seem to get run.

### CODE REVIEW

**Comment by kylebarron** [comment]
Interestingly.. there are no numpy type errors with numpy 1.19; a few on 1.20; and many on 1.21. Tox [is installing](https://github.com/cogeotiff/rio-tiler/runs/3324405145#step:5:23) numpy 1.19.5, but I can't figure out why. There's no restriction on numpy, so I'd expect it to install 1.21 (and that's what it does for me locally).

**Comment by kylebarron** [comment]
I tried to pin to numpy 1.21 in tests only... and tox can't understand that apparently 🤷‍♂️ (though pip can!).

**Comment by kylebarron** [comment]
```
ERROR: Could not find a version that satisfies the requirement numpy<1.22,>=1.21
ERROR: No matching distribution found for numpy<1.22,>=1.21
```
zero clue why pip can't find any numpy version past 1.19.5

**Comment by kylebarron** [comment]
> zero clue why pip can't find any numpy version past 1.19.5

This is because 1.19.5 was the last one to support Python 3.6.

🤦‍♂️

**Comment by vincentsarago** [comment]
done in #461

**Pull request closed without merging**
