### PR TITLE
Modified code to return as a percent value

### LINKED ISSUE #398: Percent should be percent
in 
https://github.com/cogeotiff/rio-tiler/blob/61a310f551f0b525109626e0a7d80dd27311d81b/rio_tiler/utils.py#L86

the returned value is between 0 -> 1 while it should be a percent (0 -> 100)

### PR DESCRIPTION
**Pull request by param-thakker**
closes #398

### CODE REVIEW

**Review by geospatial-jeff — APPROVED** [review]
@param-thakker LGTM, could you please run pre-commit to fix the build?

**Comment by param-thakker** [comment]
> @param-thakker LGTM, could you please run pre-commit to fix the build?

@geospatial-jeff Could you please tell me how to do it? This is my first ever contribution to OSS and I'm trying to learn!

**Comment by kylebarron** [comment]
The Contributing doc might be helpful: https://github.com/cogeotiff/rio-tiler/blob/master/CONTRIBUTING.md#contributing

**Comment by geospatial-jeff** [comment]
Yes please follow the Contributing doc to get your environment set up.  It doesn't cover retroactively running pre-commit checks, which you can do with `pre-commit run --all-files` after you've installed the hooks with `pre-commit install`.

This will apply pre-commit to all existing files in your branch, you can push the changes and that should fix the build.

**Comment by vincentsarago** [comment]
thanks for your contribution @param-thakker 🙏 

I've ran pre-commit and updated the test to make sure the `valid_percent` value is between 0 and 100.

**Pull request merged**
