### PR TITLE
Add rplumbo colormap

### PR DESCRIPTION
**Pull request by DanSchoppe**
In remote sensing, NDVI (measure of vegetation) is frequently colored red (bad) to green (good). (Sources: [0](https://pro.arcgis.com/en/pro-app/help/data/imagery/ndvi-colorized-function.htm), [1](https://crops.extension.iastate.edu/cropnews/2016/05/choosing-right-imagery-best-management-practices-color-nir-and-ndvi-imagery) )

Unfortunately, there are no red-to-green color maps supported by rio-tiler. This PR adds the "rplumbo" color map:
- Grayscale (dark-to-light) from indices 0-127
- Red-to-green from indices 128-255
Screen Shot 2019-03-11 at 9 44 40 AM

An aside: In the long-term, it would be nice if rio-tiler could take a color map (or some representation that programmatically generates a color map) via query parameters or even POST body. Is this something worth adding an issue for?

Thanks to Mapbox and all contributors for this amazing rasterio / rio-tiler toolchain!

## References:
[0] https://pro.arcgis.com/en/pro-app/help/data/imagery/ndvi-colorized-function.htm
```
The default color map is named NDVI3. Red and orange pixels represent areas with no vegetation. Yellow pixels represent areas with low to moderate vegetation. Green pixels represent areas with high vegetation density and vigor.
```

[1] https://crops.extension.iastate.edu/cropnews/2016/05/choosing-right-imagery-best-management-practices-color-nir-and-ndvi-imagery
```
Areas with Green had the highest index value, followed by Yellow and Red had the lowest.
```

### CODE REVIEW

**Comment by vincentsarago** [comment]
Thanks this awesome PR @DanSchoppe 

about ` Is this something worth adding an issue for?` this is definitely something I wanted to add. I'll open an issue right now. 

About the PR itself, would you mind adding a test here https://github.com/cogeotiff/rio-tiler/blob/master/tests/test_utils.py#L270-L279 ?

**Comment by DanSchoppe** [comment]
Thanks for the feedback, Vincent!

I was able to write a purposefully failing test, fix the test, then re-run to see it pass, so it should be good now.

**Comment by DanSchoppe** [comment]
Thanks for merging, Vincent! I'll keep an eye out for discussion around providing colormap colorization parameters at request time. I've got a couple thoughts ;-)

**Comment by vincentsarago** [comment]
Thanks again, I've merged this PR to master, but I forgot that I had the maint-1.0 branch up for this kind of PR. I should have remembered this 🤦‍♂️ 

For now it's not a big thing but if you have more PR to come I'll ask you to use maint-1.0 as base :-) 

I'll publish a new version of rio-tiler 1.1.4 later today with your change

**Comment by vincentsarago** [comment]
>  I've got a couple thoughts ;-)

@DanSchoppe feel free to start the ticket if you prefer 😄

**Comment by vincentsarago** [comment]
@DanSchoppe rio-tiler 1.1.4 is available. 
result looks great 
https://viewer.remotepixel.ca/?sceneid=LC08_L1TP_039037_20190225_20190309_01_T1&scale=1&format=png&saturation=0&contrast=0&expr=(b5-b4)%2F(b5%2Bb4)&color_map=rplumbo&rescale=-1,1#9.56/33.0304/-115.5103

Capture d’écran, le 2019-03-11 à 17 24 14

**Comment by DanSchoppe** [comment]
Awesome! Thanks for helping with this and being so responsive! The `rplumbo` could be a good default for your remotepixel viewer index tiles ;-)

**Pull request merged**
