### PR TITLE
Add grayscale colormap

### PR DESCRIPTION
**Pull request by DanSchoppe**
Similar to #90, this PR adds a grayscale colormap to the project (along with a relevant unit test).

### CODE REVIEW

**Comment by DanSchoppe** [comment]
@vincentsarago I'm not aware of the reasons for using `cogeotiff:maint-1.0`. Perhaps it's to aggregate a number of improvements in order to reduce the number of releases? Would I have a better chance at getting this into a release by PRing into `master`?

**Comment by vincentsarago** [comment]
@DanSchoppe thanks for this PR I love it.

Can you be more explicit about this PR and what it solve ? To be honest I'm not sure to fully get why it is usefull.

> I'm not aware of the reasons for using cogeotiff:maint-1.0. Perhaps it's to aggregate a number of improvements in order to reduce the number of releases? Would I have a better chance at getting this into a release by PRing into master?

Yeah the idea was to always PR on maint-1.0 (as rasterio does) and then when there is enough or important features/fix we can merge it to master and release.

**Comment by DanSchoppe** [comment]
@vincentsarago Thanks for the PR feedback. I apologize, I should have drafted an explanation in the PR description. Here's what I'm thinking:

I've got a number of float32 COGs that contain scientific values. Since tile image formats (JPG, PNG) do not support floating-point values, the only way to generate a tile containing these floating point values is to apply a reversible (although unfortunately lossy) colormap to the data.

For example, a COG with float32 values ranging from [-1, 1]. A web client requests a tile with grayscale colorization. The resulting tile has uint8 bands with values in the range [0, 255]. The web client can then re-map the [0, 255] range to the original [-1, 1] COG range to recover a (lossy) estimate of the original floating point value.

Does that make sense?

**Comment by vincentsarago** [comment]
> For example, a COG with float32 values ranging from [-1, 1]. A web client requests a tile with grayscale colorization. The resulting tile has uint8 bands with values in the range [0, 255]. The web client can then re-map the [0, 255] range to the original [-1, 1] COG range to recover a (lossy) estimate of the original floating point data.

> Does that make sense?

👋 @DanSchoppe, still I'm not fully understanding. 

If you have float data from -1 to 1, to enable the `image` creation you'll need to `rescale` it to 0-255 value (eg by using https://github.com/cogeotiff/rio-tiler/blob/master/rio_tiler/utils.py#L385-L408) so the output value is already in a `grayscale` colormap like.

**Comment by DanSchoppe** [comment]
@vincentsarago Thanks for the feedback.

I think you're right. I didn't realize I could rescale the image values without providing a colormap. This PR was essentially implementing a `null` colormap, but I see now that this is unnecessary.

**Comment by vincentsarago** [comment]
Excellent @DanSchoppe 

>  I didn't realize I could rescale the image values without providing a colormap

I should maybe add a note in the documentation, but yes `colormap` are just there to create a map to represent 1 band range value from 0-255 to a 3 band RGB image (in https://github.com/cogeotiff/rio-tiler/blob/master/rio_tiler/utils.py#L491-L563). Rescaling as to be done before passing the tile array to the `array_to_image` function

**Pull request closed without merging**
